package cpen221.mp3.wikimediator;


public class WikiResponseString {
    //RI:
    //  1. status, on assign, must be either 'success' or 'failure'
    //  2. response must be the correct response generated by wikimediator
    //  3. id is the id of the corresponding user
    //AF:
    //  AF(id) = a response ready to be converted into json file and send back to user
    private String id;
    private String status;
    private String response;

    public WikiResponseString(String id){
        this.id = id;
        this.status = "";
        this.response = "";
    }
    /**
     * set status to be equal to the parameter status
     * @param status is the status of the reponse to the client, either "success", or "failure"
     */
    public void setStatus(String status){
        this.status=status;
    }

    /**
     * set response to be equal to the parameter response
     * @param response is the response String sent to the client
     */
    public void setResponse(String response){
        this.response=response;
    }
}
